### ISSUE TITLE
Gitlab relatives urls asserts

### ISSUE THREAD

**Issue by danger89** [appleboy/server-configs#6]
During a recent Gitlab upgrade, be-ware of the warning on line 124 block, here:
https://github.com/appleboy/server-configs/blob/master/nginx/sites-available/gitlab.conf#L124

My assets didn't load fully, commenting-out this block solved my issue on Debian Omnibus installation.

**Comment by appleboy** [comment]
@danger89 Do you mean comment out https://github.com/appleboy/server-configs/blob/master/nginx/sites-available/gitlab.conf#L127-L132 ?

**Comment by danger89** [comment]
Correctly. It's not really a bug, but more a feature that can't be used when you are using relative paths. I think relative paths are used by default..

**Comment by appleboy** [comment]
I will fix this asap.

**Comment by appleboy** [comment]
fixed in #7
